name = "Max number game"
version = "0.1.0"
extra_files = "extras"
intro = "src/game/intro.lean"

[[worlds]]
name = "Max"
id = 10
levels = [
	"src/game/max/level01.lean",
	"src/game/max/level02.lean",
	"src/game/max/level03.lean",
	"src/game/max/level04.lean",
	"src/game/max/level05.lean",
	"src/game/max/level06.lean",
	"src/game/max/level07.lean",
	"src/game/max/level08.lean",
	"src/game/max/level09.lean",
	"src/game/max/level10.lean"
]

